#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind": "ClusterRoleBinding"}), expects=2
---
subjects:
#@overlay/match by=overlay.subset({"namespace": "argocd"})
- kind: ServiceAccount
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind": "Service", "metadata":{"name":"argocd-server"}})
---
spec:
  #@overlay/match missing_ok=True
  type: #@ data.values.service.type
